Repository DeveloperAcademy-POSTECH/MC3-Team6-MutekiNoIdoruPricura, pull requests merged in 2023-07, with the labels that each got.

#3 [Feat] 애플 로그인 구현
  LovelyCrane.xcodeproj/project.pbxproj
  LovelyCrane.xcodeproj/project.xcworkspace/xcuserdata/kimchoonsik.xcuserdatad/UserInterfaceState.xcuserstate
  LovelyCrane/LovelyCraneApp.swift
  LovelyCrane/Manager/AuthenticationManager.swift
  LovelyCrane/Manager/Helpers/SignInAppleHelper.swift
  LovelyCrane/Manager/TopViewControllerManager.swift
  LovelyCrane/Model/AuthDataResultModel.swift
  LovelyCrane/Model/SignWithAppleResult.swift
  LovelyCrane/RootView.swift
  LovelyCrane/View/Login/AppleLoginButton.swift
  LovelyCrane/View/Login/AuthenticationView.swift
  LovelyCrane/View/Login/SettingsView.swift
  LovelyCrane/ViewModel/LoginView/AuthenticationViewModel.swift
  LovelyCrane/ViewModel/LoginView/SettingsViewModel.swift
Labels: development

#5 [Feat] 구글 로그인 구현
  LovelyCrane.xcodeproj/project.pbxproj
  LovelyCrane.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LovelyCrane/Info.plist
  LovelyCrane/Manager/AuthenticationManager.swift
  LovelyCrane/Manager/Helpers/SignInGoogleHelper.swift
  LovelyCrane/Manager/TopViewControllerManager.swift
  LovelyCrane/Model/AuthDataResult.swift
  LovelyCrane/Model/SignWithGoogleResult.swift
  LovelyCrane/View/Login/AuthenticationView.swift
  LovelyCrane/ViewModel/LoginView/AuthenticationViewModel.swift
  LovelyCrane/ViewModel/LoginView/SettingsViewModel.swift
Labels: development

#6 [feat] 메인뷰 UI빼고 완료
  LovelyCrane.xcodeproj/project.pbxproj
  LovelyCrane/Assets.xcassets/bottle.imageset/Contents.json
  LovelyCrane/Assets.xcassets/bottle.imageset/bottle.svg
  LovelyCrane/Assets.xcassets/inbox.imageset/Contents.json
  LovelyCrane/Assets.xcassets/inbox.imageset/inbox.svg
  LovelyCrane/Assets.xcassets/inboxMessage.imageset/Contents.json
  LovelyCrane/Assets.xcassets/inboxMessage.imageset/inboxMessage.svg
  LovelyCrane/Assets.xcassets/send.imageset/Contents.json
  LovelyCrane/Assets.xcassets/send.imageset/send.svg
  LovelyCrane/Assets.xcassets/setting.imageset/Contents.json
  LovelyCrane/Assets.xcassets/setting.imageset/setting.svg
  LovelyCrane/Common/Assets.swift
  LovelyCrane/Ext+/CGSize.swift
  LovelyCrane/Ext+/Color.swift
  LovelyCrane/Ext+/UIColor.swift
  LovelyCrane/Manager/MotionManager.swift
  LovelyCrane/SpriteKit/SpriteScene.swift
  LovelyCrane/View/Main/MainView.swift
  LovelyCrane/View/ReceiveHistory/ReciveHistoryView.swift
  LovelyCrane/View/Setting/SettingView.swift
  LovelyCrane/View/WriteHistory/WriteHistoryView.swift
  LovelyCrane/View/WritePage/WriteView.swift
Labels: development

#8 [feat] FireStore data 관리
  LovelyCrane.xcodeproj/project.pbxproj
  LovelyCrane.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LovelyCrane/Model/AuthDataResult.swift
  LovelyCrane/Model/Info.swift
  LovelyCrane/Model/User.swift
  LovelyCrane/Network/FireStore/UserManager.swift
  LovelyCrane/RootView.swift
  LovelyCrane/View/Login/AuthenticationView.swift
  LovelyCrane/View/Login/NickNameView.swift
  LovelyCrane/View/Login/SettingsView.swift
Labels: ☀️Sunday, development

#16 #9/sendto firebase
  LovelyCrane.xcodeproj/project.pbxproj
  LovelyCrane.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LovelyCrane/Assets.xcassets/bottle.imageset/Contents.json
  LovelyCrane/Assets.xcassets/bottle.imageset/bottle.svg
  LovelyCrane/Assets.xcassets/inbox.imageset/Contents.json
  LovelyCrane/Assets.xcassets/inbox.imageset/inbox.svg
  LovelyCrane/Assets.xcassets/inboxMessage.imageset/Contents.json
  LovelyCrane/Assets.xcassets/inboxMessage.imageset/inboxMessage.svg
  LovelyCrane/Assets.xcassets/send.imageset/Contents.json
  LovelyCrane/Assets.xcassets/send.imageset/send.svg
  LovelyCrane/Assets.xcassets/setting.imageset/Contents.json
  LovelyCrane/Assets.xcassets/setting.imageset/setting.svg
  LovelyCrane/Common/Assets.swift
  LovelyCrane/Ext+/CGSize.swift
  LovelyCrane/Ext+/Color.swift
  LovelyCrane/Ext+/UIColor.swift
  LovelyCrane/GoogleService-Info.plist
  LovelyCrane/Info.plist
  LovelyCrane/LovelyCraneApp.swift
  LovelyCrane/Manager/AuthenticationManager.swift
  LovelyCrane/Manager/Helpers/SignInGoogleHelper.swift
  LovelyCrane/Manager/ImagePicker.swift
  LovelyCrane/Manager/MotionManager.swift
  LovelyCrane/Manager/TopViewControllerManager.swift
  LovelyCrane/Model/AuthDataResult.swift
  LovelyCrane/Model/Info.swift
  LovelyCrane/Model/SignWithGoogleResult.swift
  LovelyCrane/Model/User.swift
  LovelyCrane/Model/WriteModel.swift
  LovelyCrane/Network/FireStore/StoargeManager.swift
  LovelyCrane/Network/FireStore/UserManager.swift
  LovelyCrane/RootView.swift
  LovelyCrane/SpriteKit/SpriteScene.swift
  LovelyCrane/View/Login/AuthenticationView.swift
  LovelyCrane/View/Login/NickNameView.swift
  LovelyCrane/View/Login/SettingsView.swift
  LovelyCrane/View/Main/MainView.swift
  LovelyCrane/View/ReceiveHistory/ReciveHistoryView.swift
  LovelyCrane/View/Setting/SettingView.swift
  LovelyCrane/View/WriteHistory/WriteHistoryView.swift
  LovelyCrane/View/WritePage/WriteView.swift
  LovelyCrane/ViewModel/LoginView/AuthenticationViewModel.swift
  LovelyCrane/ViewModel/LoginView/SettingsViewModel.swift
  LovelyCrane/ViewModel/WritePage/WriteViewModel.swift
Labels: ☀️Sunday, development

#30 [Feat] splashView 관련 수정, 닉네임뷰 레이아웃 수정, 에셋 및 컬러 변경, 세팅뷰 변경(회원 탈퇴 구현)
  LovelyCrane.xcodeproj/project.pbxproj
  LovelyCrane/Assets.xcassets/AuthenticationViewImage.imageset/AuthenticationViewImage.svg
  LovelyCrane/Assets.xcassets/LaunchScreen.imageset/Contents.json
  LovelyCrane/Assets.xcassets/login.imageset/Contents.json
  LovelyCrane/Assets.xcassets/login.imageset/login.svg
  LovelyCrane/Ext+/Color+.swift
  LovelyCrane/Network/FireStore/UserManager.swift
  LovelyCrane/View/Login/AuthenticationView.swift
  LovelyCrane/View/Login/NicknameView.swift
  LovelyCrane/View/Main/MainView.swift
  LovelyCrane/View/Setting/SettingView.swift
  LovelyCrane/View/Setting/SettingView2.swift
  LovelyCrane/View/WritePage/EnlargedImageView.swift
  LovelyCrane/View/WritePage/WriteView.swift
  LovelyCrane/ViewModel/LoginView/SettingsViewModel.swift
  LovelyCrane/ViewModel/Setting/SettingViewModel.swift
Labels: development

#57 [style] WriteView 및 Custom Alert 관련 뷰 들에 custom font 적용 완료
  LovelyCrane.xcodeproj/project.xcworkspace/xcuserdata/earlysummer2.xcuserdatad/UserInterfaceState.xcuserstate
  LovelyCrane/Common/Components/CustomAlerts/CouplingAlertView.swift
  LovelyCrane/Common/Components/CustomAlerts/FadeAlertView.swift
  LovelyCrane/Common/Components/CustomAlerts/PresentAlertView.swift
  LovelyCrane/Common/Components/CustomAlerts/TouchCraneAlertView.swift
  LovelyCrane/View/WritePage/WriteView.swift
Labels: 🌊Swimmer, development

#58 [Feat] 닉네임 수정 알럿 추가 및 담당 뷰 커스텀 폰트 적용
  LovelyCrane.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LovelyCrane/Common/Components/CustomAlerts/FadeAlertView.swift
  LovelyCrane/View/Login/AuthenticationView.swift
  LovelyCrane/View/Login/NicknameView.swift
  LovelyCrane/View/ReceiveHistory/NoReceivedView.swift
  LovelyCrane/View/ReceiveHistory/ReceivedHistoryCell.swift
  LovelyCrane/View/ReceiveHistory/ReceivedHistoryView.swift
  LovelyCrane/View/Setting/SettingView.swift
  LovelyCrane/View/Setting/UpdateNicknameView.swift
  LovelyCrane/View/WriteHistory/NoWriteView.swift
  LovelyCrane/View/WriteHistory/WriteHistoryCell.swift
  LovelyCrane/View/WriteHistory/WriteHistoryView.swift
  LovelyCrane/ViewModel/Setting/SettingViewModel.swift
Labels: 🐈Toughie, development
